name: RECOVERY

on:
  workflow_dispatch:
    inputs:
      RECOVERY_URL:
        description: 'RECOVERY URL'
        required: true
        default: 'https://drive.google.com/file/d/1fkOZEBQIanFTf9D7lonz_gjNROhZjAS7/view?usp=drive_link'

env:
  RECOVERY_URL: https://oshi.at/Rpjg

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Prepare environment
      run: |
        sudo apt update
        sudo apt install -y git wget lz4 tar openssl python3 python3-pip
        pip install avbtool

    - name: Fetch image from URL
      run: |
        echo "Downloading recovery image..."
        URL="${{ github.event.inputs.RECOVERY_URL || env.RECOVERY_URL }}"
        wget "$URL" -O recovery.img --no-check-certificate
        echo "Downloaded file:"
        ls -lh recovery.img

    - name: Patch Process 1
      run: |
        chmod +x magiskboot script1.sh || true
        ./script1.sh || true

    - name: Patch Process 2
      run: |
        chmod +x script2.sh || true
        ./script2.sh || true

        echo "Generating AVB footer..."
        python3 avbtool extract_public_key --key phh.pem --output phh.pub.bin
        python3 avbtool add_hash_footer \
          --partition_name recovery \
          --partition_size $(wc -c < recovery.img) \
          --image recovery-patched.img \
          --key phh.pem \
          --algorithm SHA256_RSA4096

        mkdir -p output
        mv recovery-patched.img output/recovery.img
        cd output
        tar -cf fastbootd-recovery.tar recovery.img
        md5sum -t fastbootd-recovery.tar >> fastbootd-recovery.tar
        mv fastbootd-recovery.tar fastbootd-recovery.tar.md5
        cd ..

    - name: Upload Recovery Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Patched-Recovery
        path: ./output/*.md5
